In [35]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([1,2,3])

In [3]:
a.shape

(3,)

In [4]:
b = np.array([[1,2,3],[4,5,6]])

In [5]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [8]:
np.arange(1,10, 2)

array([1, 3, 5, 7, 9])

In [9]:
np.linspace(1,11, num=11)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [10]:
b[0][1]

2

In [11]:
b[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
b[:,1]

array([2, 5])

In [13]:
b.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
b.T # transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
for i in range(b.shape[0]):
    for j in range(b.shape[1]):
        b[i,j] = b[i,j]*2

In [16]:
b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [17]:
b*2

array([[ 4,  8, 12],
       [16, 20, 24]])

In [18]:
b>3

array([[False,  True,  True],
       [ True,  True,  True]])

In [19]:
b/2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [20]:
b>3

array([[False,  True,  True],
       [ True,  True,  True]])

In [21]:
b = b/2

In [22]:
np.mean(b)

3.5

In [23]:
np.mean(b, axis=1) # rows

array([2., 5.])

In [26]:
np.mean(b, axis=-1)

array([2., 5.])

In [29]:
b2 = b*2

In [34]:
np.concatenate([b,b2], axis=0)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [38]:
df = pd.read_csv('DATA/cw4/Zadanie_1.csv', sep=';')

In [41]:
df.shape

(60, 16)

In [44]:
np_arr = np.genfromtxt('DATA/cw4/Zadanie_1.csv', delimiter=';')

array([[         nan,          nan,          nan,          nan,
                 nan,          nan,          nan,          nan,
                 nan,          nan,          nan,          nan,
                 nan,          nan,          nan,          nan],
       [3.600000e+01, 2.700000e+01, 7.100000e+01, 8.100000e+00,
        3.340000e+00, 1.140000e+01, 8.150000e+01, 3.243000e+03,
        8.800000e+00, 4.260000e+01, 1.170000e+01, 2.100000e+01,
                 nan, 5.900000e+01, 5.900000e+01, 9.218700e+02],
       [3.500000e+01, 2.300000e+01, 7.200000e+01, 1.110000e+01,
        3.140000e+00, 1.100000e+01, 7.880000e+01, 4.281000e+03,
        3.600000e+00, 5.070000e+01, 1.440000e+01, 8.000000e+00,
        1.000000e+01, 3.900000e+01, 5.700000e+01, 9.978750e+02],
       [4.400000e+01, 2.900000e+01, 7.400000e+01, 1.040000e+01,
        3.210000e+00, 9.800000e+00, 8.160000e+01, 4.260000e+03,
        8.000000e-01, 3.940000e+01,          nan, 6.000000e+00,
        6.000000e+00, 3.300000e+01, 5